CASE 

WHEN NOMBRE_TERRITORIO ="T.BCL" THEN 6
WHEN NOMBRE_TERRITORIO ="T.BE CENTRAL" THEN 5
WHEN NOMBRE_TERRITORIO="T.BE REG.2" THEN 4
WHEN NOMBRE_TERRITORIO="T.BE REG.3" THEN 3
WHEN NOMBRE_TERRITORIO="T.BE REG.1" THEN 2
WHEN NOMBRE_TERRITORIO="T.B.INSTITUCIONAL" THEN 1

END

-----------------------------------

CASE 

WHEN NBR_OFICINA ="BE LIMA 2" THEN 20
WHEN NBR_OFICINA ="BE AREQUIPA" THEN 19
WHEN NBR_OFICINA ="BE HUANCAYO" THEN 18
WHEN NBR_OFICINA ="BE DOS DE MAYO" THEN 17
WHEN NBR_OFICINA ="BE LIMA 1" THEN 16
HEN NBR_OFICINA ="BE PIURA" THEN 15
WHEN NBR_OFICINA ="BE LA MOLINA" THEN 14
WHEN NBR_OFICINA ="BE CHICLAYO" THEN 13
WHEN NBR_OFICINA ="BE CUSCO" THEN 12
WHEN NBR_OFICINA ="BE COLONIAL" THEN 11
WHEN NBR_OFICINA ="BE CHACARILLA" THEN 10
WHEN NBR_OFICINA ="BE LIMA NORTE" THEN 9
WHEN NBR_OFICINA ="BE REPÚBLICA DE PANAMÁ" THEN 8
WHEN NBR_OFICINA ="BE MIRAFLORES" THEN 7
WHEN NBR_OFICINA ="BE CHINCHA" THEN 6
WHEN NBR_OFICINA ="BE CALLAO" THEN 5
WHEN NBR_OFICINA ="BE SAN ISIDRO" THEN 4
WHEN NBR_OFICINA ="BE TRUJILLO" THEN 3
WHEN NBR_OFICINA ="BE LIMA" THEN 2
WHEN NBR_OFICINA ="BE SANTA CRUZ" THEN 1

END


---------------------------------

CASE 
    WHEN NOMB. REGION="T.BE CENTRAL" THEN 6
    WHEN NOMB. REGION="T.BE REG.2" THEN 5
    WHEN NOMB. REGION="T.BCL" THEN 4
	WHEN NOMB. REGION="T.BE REG.1" THEN 3
	WHEN NOMB. REGION="T.BE REG.3" THEN 2
    WHEN NOMB. REGION ="T.BINS" THEN 1
END

CASE 
    WHEN NOMB. REGION="T.BE REG.2" THEN 6
	WHEN NOMB. REGION="T.BE CENTRAL" THEN 5
    WHEN NOMB. REGION="T.BE REG.1" THEN 4
	WHEN NOMB. REGION="T.BINS" THEN 3
	WHEN NOMB. REGION="T.BCL" THEN 2
    WHEN NOMB. REGION ="T.BE REG.3" THEN 1
END


CASE 

    WHEN OFICINA ="BE AREQUIPA" THEN 20
    WHEN OFICINA ="BE CHACARILLA" THEN 19
    WHEN OFICINA ="BE LIMA CENTRO" THEN 18
    WHEN OFICINA ="BE LA MOLINA" THEN 17
    WHEN OFICINA ="BE NORTE CHICO" THEN 16
    WHEN OFICINA ="BE MIRAFLORES" THEN 15
    WHEN OFICINA = "BE REPÚBLICA DE PANAMÁ"  THEN 14
    WHEN OFICINA ="BE DOS DE MAYO" THEN 13
    HEN OFICINA ="BE SANTA CRUZ" THEN 12
    HEN OFICINA ="BE LIMA 1" THEN 11
    WHEN OFICINA ="BE LIMA OESTE 2" THEN 10
    WHEN OFICINA ="BE SUR CHICO" THEN 9
    WHEN OFICINA ="BE LIMA ORIENTE" THEN 8
    WHEN OFICINA ="BE SAN ISIDRO" THEN 7
    WHEN OFICINA ="BE LIMA OESTE 1" THEN 6
    WHEN OFICINA ="BE PIURA" THEN 5
    WHEN OFICINA ="BE CUSCO" THEN 4
    WHEN OFICINA ="BE TRUJILLO" THEN 3
    WHEN OFICINA ="BE CHICLAYO" THEN 2
    WHEN OFICINA ="BE HUANCAYO" THEN 1
    
END

------------------------------------------------------------------------------------------------------------------------

CASE 

    WHEN OFICINA ="BE LIMA ORIENTE" THEN 20
    WHEN OFICINA ="BE REPÚBLICA DE PANAMÁ" THEN 19
    WHEN OFICINA ="BE SUR CHICO" THEN 18
    WHEN OFICINA ="BE LA MOLINA" THEN 17
    WHEN OFICINA ="BE CHACARILLA" THEN 16
    WHEN OFICINA ="BE AREQUIPA" THEN 15
    WHEN OFICINA ="BE HUANCAYO" THEN 14
    WHEN OFICINA ="BE TRUJILLO" THEN 13
    WHEN OFICINA ="BE MIRAFLORES" THEN 12
    WHEN OFICINA ="BE PIURA" THEN 11
    WHEN OFICINA ="BE NORTE CHICO" THEN 10
    WHEN OFICINA = "BE SANTA CRUZ"  THEN 9
    WHEN OFICINA ="BE LIMA CENTRO" THEN 8
    WHEN OFICINA ="BE DOS DE MAYO" THEN 7
    WHEN OFICINA ="BE LIMA OESTE 2" THEN 6
    WHEN OFICINA ="BE CHICLAYO" THEN 5
    WHEN OFICINA ="BE SAN ISIDRO" THEN 4
    WHEN OFICINA ="BE LIMA 1" THEN 3
    WHEN OFICINA ="BE LIMA OESTE 1" THEN 2
    WHEN OFICINA ="BE CUSCO" THEN 1
    
END



Arturo medina disponible
Kat disponible
Rep panama ana pereyra dispo
Aurea y maria campos piura pre y post
Trujillo pablo valiente por jose felix  victor hugo dias por pablo valiente
Chacarilla  juan cuadra por ana alamanza
Por julio vega rafael zevallos
Sanya cruz  por juan cuadra ana almanza
Aqp por baylon paul jurado  por priscila va luciana cornejo por luciana gianca vilca
Cusco  cecilia por paul y giossy por cecilia
Dos de mayo: ariana por mirko,