* DIARIA MAS PRELIMINAR , NO COJE PRELIMINAR CUANDO YA HAY BASE DE CIERRE



SELECT A.FECPRO,A.FECAPE,A.NUMCNT,A.CODEPW,A.PLAOPE,
A.CODOFI,B.DES_OFICINA OFICINA,
B.COD_TERRITORIO, B.DES_TERRITORIO,
A.CODCLI,D.NOMBRE1 NOMBRE_EMPRESA,
A.GESLOC,C.RIDESCRI,
A.NUMDOC,
SUM(A.IMPSOL) as importe,
SUM(A.NUMOPE) as numoperacion
FROM USRFINDATA.STG_FACTUNICAD A
LEFT JOIN USRFINDATA.ODS_OFICINA B ON B.COD_OFICINA=A.CODOFI
LEFT JOIN USRFINDATA.STG_PMDT700 C ON C.RICGESTO=A.GESLOC
LEFT JOIN usrfindata.Stg_pe01 D ON D.CENTRAL=A.CODCLI
WHERE A.FECPRO IN (select FECPRO from USRFINDATA.STG_FACTUNICAD
WHERE FECPRO
 in (SELECT FECPRO From USRFINDATA.STG_FACTUNICAD  Where FECPRO > SYSDATE - 15 Group By FECPRO, to_char(FECPRO, 'Month'))
AND
to_char(FECPRO, 'Month')
 NOT IN (Select to_char(MAX(FECPRO),'Month') as fp From USRFINDATA.STG_FACTUNICAM Where FECPRO > SYSDATE - 15 Group By to_char(FECPRO, 'Month'))
)
 AND B.FECPRO = (SELECT MAX(FECPRO) as fp FROM USRFINDATA.ODS_OFICINA)
  AND C.FECPRO = (SELECT MAX(FECPRO) as fp FROM USRFINDATA.STG_PMDT700)
   AND D.FECPRO = (SELECT MAX(FECPRO) as fp FROM usrfindata.Stg_pe01)
AND ((A.CODCPT_R IN ('201','216','227','228')) OR (A.CODCPT_R IN ('271','272') AND A.CODCLA IS NOT NULL) OR
    (A.CODCPT_R='205' AND A.CODAPL<>'CD') OR (A.CODCPT_R='273' AND TRIM(A.CODCLA)='TKT'))
AND B.DES_BANCA IN ('AREA BCA.EMP. Y CORP','AREA B.INSTITUCIONAL')
AND A.CODEPW IN (
'0159501',
'0159502') -- LEASING -- PCOM -- COMEX EXP,IMP,FORFAITING -- CARTA CRED IMP,STAND BY LETTER, CARTA CRED EX -- LETRAS -- FACTORING
GROUP BY A.FECPRO,A.FECAPE,A.NUMCNT,A.CODEPW,A.PLAOPE,A.CODOFI,B.DES_OFICINA, A.CODCLI,D.NOMBRE1,A.GESLOC,C.RIDESCRI, A.NUMDOC,B.COD_TERRITORIO, B.DES_TERRITORIO