SELECT * FROM USRFINDATA.BWH_RESULTADO@BSIBPDW0@UFINRIE

SELECT * FROM USRFINDATA.ODS_OFICINA@BSIBPDW0@UFINRIE
WHERE FECPRO='30/06/2022'
AND COD_BANCA='2685'
SELECT * FROM USRFINDATA.STG_PMDT028_R@BSIBPDW0@UFINRIE

--------------------------------------------------
SELECT * FROM USRFINDATA.BWH_RESULTADO@BSIBPDW0@UFINRIE A
JOIN USRFINDATA.STG_PMDT028_R@BSIBPDW0@UFINRIE B ON (A.FEC_PROCESO=B.FECPRO AND A.COD_CLIENTE=B.NUMCLIEN) AND B.TIPOGES=1
JOIN USRFINDATA.ODS_OFICINA@BSIBPDW0@UFINRIE C ON A.COD_OFICINA_R=C.COD_OFICINA AND C.FECPRO='30/06/2022' AND C. COD_BANCA IN ('2865','2661')
WHERE A.FEC_PROCESO='30/06/2022'

--------------------------------------

SELECT FEC_PROCESO,DES_OFICINA,DES_TERRITORIO,DES_BANCA,COD_GESTOR,COD_CLIENTE
,(C.NOMBRE1||C.NOMBRE2||C.NOMBRE3)  as DES_CLIENTE,
DES_EPIGRAFE,SUM(IMP_SALMECTR),SUM(IMP_SALPUCTR)
FROM USRFINDATA.STG_SALDOIDA7V@BSIBPDW0@UFINRIE A
JOIN USRFINDATA.STG_EPIGRAFEG@BSIBPDW0@UFINRIE EG ON A.COD_EPIWEB >= EG.LIMITE_INF AND A.COD_EPIWEB < EG.LIMITE_SUP AND EG.CLASE = 'BBA' AND 
  EG.ORDEN IN ('50')
JOIN USRFINDATA.ODS_OFICINA@BSIBPDW0@UFINRIE B ON A.COD_OFICINA=B.COD_OFICINA AND B.FECPRO='30/06/2022' AND B.COD_BANCA IN ('2685','2661')
LEFT JOIN (           
           SELECT * FROM USRFINDATA.stg_pe01@BSIBPDW0@UFINRIE WHERE fecpro=(SELECT MAX(fecpro) FROM USRFINDATA.stg_pe01@BSIBPDW0@UFINRIE ) 
           ) C ON A.COD_CLIENTE=C.CENTRAL


WHERE FEC_PROCESO IN (SELECT FEC_ULTMES FROM USRFINDATA.ODS_CALENDARIO@BSIBPDW0@UFINRIE 
WHERE FEC_ULTMES > '01/01/2022' AND FEC_ULTMES < SYSDATE GROUP BY FEC_ULTMES)
 
GROUP BY  COD_GESTOR,COD_CLIENTE,DES_EPIGRAFE,FEC_PROCESO,DES_OFICINA,DES_TERRITORIO,DES_BANCA,(C.NOMBRE1||C.NOMBRE2||C.NOMBRE3)


--------------------------------------------------------------------------------------------------------

SELECT * FROM USRFINDATA.FT_COMISION_MIG@BSIBPDW0@UFINRIE  FC
INNER JOIN USRFINDATA.ODS_PARAMETRO@BSIBPDW0@UFINRIE  OP ON OP.COD_CLASE='BCINSER' AND
                                       OP.COD_TIPPARAM='CTAR'    AND
                                       RPAD(FC.COD_CUENTA,15,'0')=OP.COD_PARAMINI
-- MODIFICAR FEC_PROCESO SEGÚN EL PERIODO REQUERIDO
WHERE FC.FEC_PROCESO='30-04-2022'


------------------------------------------------------------

SELECT * FROM USRFINDATA.FT_COMISION_MIG@BSIBPDW0@UFINRIE  FC
INNER JOIN USRFINDATA.ODS_PARAMETRO@BSIBPDW0@UFINRIE  OP ON OP.COD_CLASE='BCINSER' AND
                                       OP.COD_TIPPARAM='CTAR'    AND
                                       RPAD(FC.COD_CUENTA,15,'0')=OP.COD_PARAMINI
-- MODIFICAR FEC_PROCESO SEGÚN EL PERIODO REQUERIDO
WHERE FC.FEC_PROCESO='30-06-2022' AND (FC.COD_EPIGRAFE  = '3499001' OR FC.COD_EPIGRAFE  = '3273701' )

--------------------------------------------------------------------------------------------------


SELECT * FROM USRFINDATA.BWH_RESULTADO@BSIBPDW0@UFINRIE A
JOIN USRFINDATA.STG_PMDT028_R@BSIBPDW0@UFINRIE B ON (A.FEC_PROCESO=B.FECPRO AND A.COD_CLIENTE=B.NUMCLIEN) AND B.TIPOGES=1
JOIN USRFINDATA.ODS_OFICINA@BSIBPDW0@UFINRIE C ON A.COD_OFICINA_R=C.COD_OFICINA AND C.FECPRO='30/06/2022' AND C. COD_BANCA IN ('2865','2661')
WHERE A.FEC_PROCESO='30/06/2022'




SELECT FEC_PROCESO,DES_OFICINA,DES_TERRITORIO,DES_BANCA,COD_GESTOR,COD_CLIENTE
,(C.NOMBRE1||C.NOMBRE2||C.NOMBRE3)  as DES_CLIENTE,
DES_EPIGRAFE,SUM(IMP_SALMECTR),SUM(IMP_SALPUCTR)
FROM USRFINDATA.STG_SALDOIDA7V@BSIBPDW0@UFINRIE A
JOIN USRFINDATA.STG_EPIGRAFEG@BSIBPDW0@UFINRIE EG ON A.COD_EPIWEB >= EG.LIMITE_INF AND A.COD_EPIWEB < EG.LIMITE_SUP AND EG.CLASE = 'BBA' AND 
  EG.ORDEN IN ('50')
JOIN USRFINDATA.ODS_OFICINA@BSIBPDW0@UFINRIE B ON A.COD_OFICINA=B.COD_OFICINA AND B.FECPRO='30/06/2022' AND B.COD_BANCA IN ('2685','2661')
LEFT JOIN (           
           SELECT * FROM USRFINDATA.stg_pe01@BSIBPDW0@UFINRIE WHERE fecpro=(SELECT MAX(fecpro) FROM USRFINDATA.stg_pe01@BSIBPDW0@UFINRIE ) 
           ) C ON A.COD_CLIENTE=C.CENTRAL


WHERE FEC_PROCESO IN (SELECT FEC_ULTMES FROM USRFINDATA.ODS_CALENDARIO@BSIBPDW0@UFINRIE 
WHERE FEC_ULTMES > '01/01/2022' AND FEC_ULTMES < SYSDATE GROUP BY FEC_ULTMES)
 
GROUP BY  COD_GESTOR,COD_CLIENTE,DES_EPIGRAFE,FEC_PROCESO,DES_OFICINA,DES_TERRITORIO,DES_BANCA,(C.NOMBRE1||C.NOMBRE2||C.NOMBRE3)



SELECT * FROM USRFINDATA.FT_COMISION_MIG@BSIBPDW0@UFINRIE  FC
INNER JOIN USRFINDATA.ODS_PARAMETRO@BSIBPDW0@UFINRIE  OP ON OP.COD_CLASE='BCINSER' AND
                                       OP.COD_TIPPARAM='CTAR'    AND
                                       RPAD(FC.COD_CUENTA,15,'0')=OP.COD_PARAMINI
-- MODIFICAR FEC_PROCESO SEGÚN EL PERIODO REQUERIDO
WHERE FC.FEC_PROCESO='30-06-2022' AND ( FC.COD_EPIGRAFE  = '3273701' OR FC.COD_EPIGRAFE  = '3273301')

